//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRDProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRDLAB
    {
        public int ID { get; set; }
        public string Text1 { get; set; }
        public string Text2 { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> DTANDTIME { get; set; }
    }
}
